import { test, expect } from '@playwright/test';

test('CodeGen', async ({ page }) => {
  await page.goto('https://demotestivps.com/adminpaneltemplate_v2/bo/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div').filter({ hasText: 'Login Success' }).nth(1).click();
//   await page.getByText('admin', { exact: true }).click();
  await page.locator('#kt_app_sidebar_menu').getByRole('link', { name: ' Dashboard' }).click();
  await page.locator('#kt_app_sidebar_menu').getByRole('link', { name: ' AI Earning Dashboard' }).click();
  //await page.locator('#kt_scrolltop').click();
  await page.locator('#kt_app_sidebar_menu').getByText('Admin', { exact: true }).click();
  await page.getByRole('link', { name: 'Admin Lists' }).click();
  await page.getByRole('button', { name: 'Add New Admin' }).click();
  await page.getByRole('textbox', { name: 'Fullname' }).fill('testadmin');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('testadmin1');
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('1234');
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('12341');
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('234');
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('2344');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('#adminhidePasswordIconcf > .path4').click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('1234');
  await page.locator('#adminhidePasswordIconcf > .path4').click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Admin Created Successfully').click();
  await page.getByRole('link', { name: 'Actions ' }).first().click();
  await page.getByText('Edit').nth(4).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('testadmin@test.in');
  await page.getByRole('checkbox').nth(1).uncheck();
  await page.getByRole('checkbox').nth(3).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Actions ' }).first().click();
  await page.getByText('Change Password').first().click();
  await page.getByRole('textbox', { name: 'Enter New Password' }).click();
  await page.getByRole('textbox', { name: 'Enter New Password' }).fill('123');
  await page.getByRole('textbox', { name: 'Enter Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Enter Confirm Password' }).fill('123');
  await page.getByRole('button', { name: 'Change' }).click();
  await page.getByRole('img', { name: 'user' }).click();
  await page.getByRole('link', { name: 'Sign Out' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('testadmin1');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('img', { name: 'user' }).click();
  await page.getByText('testadmin1').click();
  await page.getByRole('link', { name: 'Sign Out' }).click();
});