from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("https://www.demoblaze.com/index.html")
    page.locator('//a[@id="login2"]').click()
    #Login
    page.locator('//input[@id="loginusername"]').fill('palani@test.in')
    page.locator('//input[@id="loginpassword"]').fill('user')
    page.wait_for_timeout(2000)
    page.locator('//button[text()="Log in"]').click()
    page.wait_for_timeout(5000)
    #Products
    page.locator('//a[text()="Samsung galaxy s6"]').click()
    page.wait_for_timeout(5000)
    page.wait_for_selector('//a[text()="Add to cart"]').click(force=True)
    page.on('dialog',lambda x:x.accept())
    page.wait_for_timeout(5000)
    #Cart
    # page.wait_for_selector('//a[text()="Cart"]').click()
    page.wait_for_timeout(3000)
    page.wait_for_selector('//a[@id="cartur"]').click()
    page.wait_for_timeout(3000)
    page.wait_for_selector('//button[text()="Place Order"]').click()
    page.wait_for_timeout(3000)
    page.locator('//input[@id="name"]').fill('TestUser')
    page.locator('//input[@id="country"]').fill('India')
    page.locator('//input[@id="city"]').fill('TVL')
    page.locator('//input[@id="card"]').fill('3877373737')
    page.locator('//input[@id="month"]').fill('03')
    page.locator('//input[@id="year"]').fill('2026')
    page.wait_for_timeout(3000)
    page.wait_for_selector('//button[@onclick="purchaseOrder()"]').click()
    page.wait_for_timeout(3000)
    page.locator('//button[text()="OK"]').click()
    page.wait_for_timeout(5000)
    page.wait_for_selector('//a[text()="Contact"]').click()
    page.wait_for_timeout(3000)
    page.locator('//input[@id="recipient-email"]').fill('palani@test.in')
    page.locator('//input[@id="recipient-name"]').fill('TestUser')
    page.locator('//textarea[@id="message-text"]').fill('test address,xyz')
    page.wait_for_timeout(3000)
    page.wait_for_selector('//button[@onclick="send()"]').click()
    page.on('dialog',lambda x:x.accept())
    page.wait_for_timeout(3000)
    page.wait_for_selector('//a[text()="About us"]').click()
    page.wait_for_timeout(3000)
    page.wait_for_selector('//button[@class="close"]').click()
    page.wait_for_selector('//a[@onclick="logOut()"]').click()
    page.wait_for_timeout(3000)