import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demotestivps.com/adminpaneltemplate_v2/bo/login/');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('#kt_app_sidebar_menu').getByRole('link', { name: ' Dashboard' }).click();
  await page.getByRole('button', { name: ' Filter' }).click();
  await page.getByRole('textbox', { name: 'Date From' }).click();

  await page.locator('.arrowUp').first().click();
  await page.locator('.arrowDown').first().click();
  await page.locator('.arrowDown').first().click();
  await page.locator('.arrowDown').first().click();
  await page.getByLabel('January 1, 2024').click();
  await page.getByRole('textbox', { name: 'Date To' }).click();
  await page.getByLabel('January 9, 2026').click();
  await page.getByRole('textbox', { name: 'Date To' }).fill('09-01-2026');
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('tab', { name: 'Today' }).click();
  await page.getByRole('tab', { name: 'Week' }).click();
  await page.getByRole('tab', { name: 'Month' }).click();
  await page.locator('#kt_app_sidebar_menu').getByRole('link', { name: ' AI Earning Dashboard' }).click();
  await page.locator('#kt_app_sidebar_menu').getByText('Admin', { exact: true }).click();
  await page.getByRole('link', { name: 'Admin Lists' }).click();
  await page.getByRole('button', { name: 'Add New Admin' }).click();
  await page.getByRole('textbox', { name: 'Fullname' }).fill('n');
  await page.getByRole('textbox', { name: 'Fullname' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Fullname' }).fill('');
  await page.getByRole('textbox', { name: 'Fullname' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Fullname' }).fill('Newadmin');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('n');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('newadmin');
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('1234');
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('1234');
  await page.locator('#adminhidePasswordIconcf > .path4').click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: ' Filter' }).click();
  await page.getByRole('textbox', { name: 'Login From' }).click();
  await page.locator('.arrowDown').first().click();
  await page.getByLabel('January 1, 2025').click();
  await page.getByRole('textbox', { name: 'Login From' }).fill('01-01-2025');
  await page.getByRole('textbox', { name: 'Login To' }).click();
  await page.getByLabel('January 9, 2026').click();
  await page.getByRole('textbox', { name: 'Login To' }).fill('09-01-2026');
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByLabel('', { exact: true }).uncheck();
  await page.goto('https://demotestivps.com/adminpaneltemplate_v2/bo/Admin/');
  await page.getByRole('row', { name: 'Test TestQA 25-11-2025 03:14:' }).getByLabel('', { exact: true }).check();
  await page.goto('https://demotestivps.com/adminpaneltemplate_v2/bo/Admin/');
  await page.getByRole('link', { name: 'Actions ' }).first().click();
  await page.getByText('Edit').nth(4).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin1');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://demotestivps.com/adminpaneltemplate_v2/bo/Admin/');
  await page.getByRole('link', { name: 'Actions ' }).first().click();
  await page.getByText('Change Password').first().click();
  await page.getByRole('textbox', { name: 'Enter New Password' }).click();
  await page.getByRole('textbox', { name: 'Enter New Password' }).fill('123');
  await page.getByRole('textbox', { name: 'Enter Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Enter Confirm Password' }).fill('1233');
  await page.locator('#hidePasswordIconcf > .path4').click();
  await page.getByRole('textbox', { name: 'Enter Confirm Password' }).fill('123');
  await page.getByRole('button', { name: 'Change' }).click();
  await page.getByRole('link', { name: 'Admin Activity Log' }).click();
  await page.getByRole('tab', { name: 'Today' }).click();
  await page.getByRole('tab', { name: 'Week' }).click();
  await page.getByRole('tab', { name: 'Month' }).click();
  await page.getByRole('tab', { name: '2026' }).click();
  await page.getByRole('button', { name: ' Filter' }).click();
  await page.getByRole('textbox', { name: 'Date From' }).click();
  await page.getByLabel('January 1,').first().click();
  await page.getByRole('textbox', { name: 'Date From' }).fill('01-01-2026');
  await page.getByRole('textbox', { name: 'Date To' }).click();
  await page.getByLabel('January 9,').nth(1).click();
  await page.getByRole('textbox', { name: 'Date To' }).fill('09-01-2026');
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('link', { name: 'Admin Service Group' }).click();
  await page.goto('https://demotestivps.com/adminpaneltemplate_v2/bo/Service/');
  await page.getByRole('button', { name: 'Add New Role' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').press('CapsLock');
  await page.getByRole('textbox').fill('New ');
  await page.getByRole('textbox').press('CapsLock');
  await page.getByRole('textbox').fill('New Test ');
  await page.getByRole('textbox').press('CapsLock');
  await page.getByRole('textbox').fill('New Test Role');
  await page.locator('#Dashboard_toggle').check();
  await page.locator('#Ai_Earning_Dashboard_toggle').first().check();
  await page.getByRole('cell', { name: 'Admin', exact: true }).locator('#Admin_Management_toggle').check();
  await page.getByRole('cell', { name: 'User', exact: true }).locator('#User_Management_toggle').check();
  await page.locator('#User_Management_toggle').nth(3).uncheck();
  await page.getByRole('cell', { name: 'Report', exact: true }).locator('#Report_toggle').check();
  await page.locator('#Report_toggle').nth(5).uncheck();
  await page.locator('#Report_toggle').nth(4).uncheck();
  await page.getByRole('cell', { name: 'Earning Report' }).locator('#Earning_Report_toggle').check();
  await page.getByRole('cell', { name: 'Withdrawal Report' }).locator('#Withdrawal_Report_toggle').check();
  await page.getByRole('cell', { name: 'System', exact: true }).locator('#System_Management_toggle').check();
  await page.getByRole('cell', { name: 'Notice' }).locator('#Notice_toggle').check();
  await page.locator('#Notice_toggle').nth(2).uncheck();
  await page.locator('#Notice_toggle').nth(1).uncheck();
  await page.getByRole('cell', { name: 'Language', exact: true }).locator('#Language_Management_toggle').check();
  await page.locator('#Ticketing_System_toggle').first().check();
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button', { name: 'Edit Role' }).first().click();
  await page.locator('#Ai_Earning_Dashboard_toggle').nth(1).uncheck();
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('link', { name: 'View Role' }).first().click();
  await page.locator('#kt_scrolltop').click();
  await page.locator('#kt_app_sidebar_menu').getByText('User', { exact: true }).click();
  await page.getByRole('link', { name: 'User List' }).click();
});